on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Only for tags matching vX.Y.Z

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previous_tag
        run: |
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "Previous tag: ${PREVIOUS_TAG}"
          echo ::set-output name=tag::${PREVIOUS_TAG}
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        id: generate_changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          user: gushernobindsme
          project: create-release-test
          sinceTag: ${{ steps.previous_tag.outputs.tag }}
          stripHeaders: true
          stripGeneratorNotice: true
      - name: Read Changelog # Workaround https://github.com/heinrichreimer/action-github-changelog-generator/issues/7
        id: read_changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.read_changelog.outputs.content }}
          draft: false
          prerelease: false
